# Copyright Casey Carter 2015-2017

# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE.txt or copy at http://boost.org/LICENSE_1_0.txt)

dist: xenial
language: python
python: "3.7"

cache:
  directories:
    - ${TRAVIS_BUILD_DIR}/deps/cmake-3.14.6
    - ${HOME}/.conan/data

matrix:
  include:
    - env: GCC_VERSION=8 BUILD_TYPE=Debug
      os: linux
      addons: &gcc8
        apt:
          packages:
            - g++-8
            - ninja-build
          sources:
            - ubuntu-toolchain-r-test

    - env: GCC_VERSION=8 BUILD_TYPE=Release
      os: linux
      addons: *gcc8

    - env: CLANG_VERSION=6.0 BUILD_TYPE=Release
      os: linux
      addons: &clang6
        apt:
          packages:
            - clang-6.0
            - libstdc++-6-dev
            - ninja-build
          sources:
            - llvm-toolchain-xenial-6.0
            - ubuntu-toolchain-r-test
            - sourceline: 'deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-5.0 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'

before_install:
  - if [ -n "$GCC_VERSION" ]; then export CXX="g++-${GCC_VERSION}" CC="gcc-${GCC_VERSION}"; fi
  - if [ -n "$CLANG_VERSION" ]; then export CXX="clang++-${CLANG_VERSION}" CC="clang-${CLANG_VERSION}"; fi
  - which $CC
  - which $CXX
  - $CXX --version
  - ninja --version

install:
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir -p "${DEPS_DIR}" && cd "${DEPS_DIR}"
  ############################################################################
  # Install a recent CMake (unless already installed on OS X)
  ############################################################################
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      CMAKE_VERSION=3.14.6
      if [[ -z "$(ls -A ${DEPS_DIR}/cmake-${CMAKE_VERSION}/bin)" ]]; then
        CMAKE_URL="https://cmake.org/files/v3.14/cmake-3.14.6-Linux-x86_64.tar.gz"
        mkdir -p "cmake-${CMAKE_VERSION}" && travis_retry wget --no-check-certificate --quiet -O - "${CMAKE_URL}" | tar --strip-components=1 -xz -C "cmake-${CMAKE_VERSION}"
      fi
      export PATH="${DEPS_DIR}/cmake-${CMAKE_VERSION}/bin:${PATH}"
    fi
  ############################################################################
  # Install conan
  ############################################################################
  - pip install conan
  - conan remote add onebaseroach https://api.bintray.com/conan/y4n9squared/onebaseroach
  - conan remote add mputsz https://api.bintray.com/conan/mpusz/conan-mpusz

script:
  - cd "${TRAVIS_BUILD_DIR}"
  - cmake --version
  - cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_CXX_FLAGS="${CXX_FLAGS}" -DRUN_TESTS_POSTBUILD=ON
  - cmake --build build