# Copyright Casey Carter 2015-2017

# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE.txt or copy at http://boost.org/LICENSE_1_0.txt)

dist: xenial
language: python
python: "3.7"

matrix:
  include:
    - env: GCC_VERSION=8 BUILD_TYPE=Debug
      os: linux
      addons: &gcc8
        apt:
          packages:
            - g++-8
            - ninja-build
            - cmake
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'deb https://apt.kitware.com/ubuntu/ xenial main'
              key_url: 'https://apt.kitware.com/keys/kitware-archive-latest.asc'

    - env: GCC_VERSION=8 BUILD_TYPE=Release
      os: linux
      addons: *gcc8

before_install:
  - if [ -n "$GCC_VERSION" ]; then export CXX="g++-${GCC_VERSION}" CC="gcc-${GCC_VERSION}"; fi
  - which $CC
  - which $CXX
  - $CXX --version
  - ninja --version

install:
  ############################################################################
  # Install conan
  ############################################################################
  - pip install conan
  - conan remote add onebaseroach https://api.bintray.com/conan/y4n9squared/onebaseroach
  - conan remote add mputsz https://api.bintray.com/conan/mpusz/conan-mpusz

script:
  - cd "${TRAVIS_BUILD_DIR}"
  - cmake --version
  - cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_CXX_FLAGS="${CXX_FLAGS}"
  - cmake --build build