name: ranges_code_samples workflow
on: [pull_request]

jobs:
  ubuntu:
    strategy:
      matrix:
        image: [gcc8]
        build_type: [Debug, Release]
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - name: run docker
        run: docker run --rm -v $GITHUB_WORKSPACE:/home/conan/repo --env BUILD_TYPE=${{ matrix.build_type }} conanio/${{ matrix.image }} /home/conan/repo/ci/build.sh
  windows:
    strategy:
      matrix:
        build_type: [Debug, Release]
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@master
      - name: build docker
        run: docker image build -f ci\\Dockerfile.vs -t msvc_16 .
      - name: run docker
        run: docker run --rm -v %GITHUB_WORKSPACE%:C:\\Users\\ContainerAdministrato\\repo --env BUILD_TYPE=${{ matrix.build_type }} msvc_16 C:\\Users\\ContainerAdministrato\\repo\\ci\\build.bat
