name: ranges_code_samples workflow
on:
  pull_request:
  push:
    branches: master

jobs:
  ubuntu:
    strategy:
      matrix:
        image: [gcc8]
        build_type: [Debug, Release]
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - name: run docker
        run: docker run --rm -v $GITHUB_WORKSPACE:/home/conan/repo conanio/${{ matrix.image }} cmake -DBUILD_TYPE=${{ matrix.build_type }} -P /home/conan/repo/ci/build.cmake
        
  windows-docker:
    strategy:
      matrix:
        build_type: [Debug, Release]
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@master
      - name: build docker
        run: docker build -f ci\Dockerfile.vs -t msvc_16 ci
      - name: run docker
        run: docker run --rm -v %GITHUB_WORKSPACE%:C:\Users\ContainerAdministrator\repo msvc_16 cmake -DBUILD_TYPE=${{ matrix.build_type }} -P C:\Users\ContainerAdministrator\repo\ci\build.cmake
