name: ranges_code_samples workflow
on:
  pull_request:
  push:
    branches: master

jobs:
  ubuntu:
    strategy:
      matrix:
        image: [gcc8]
        build_type: [Debug, Release]
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - name: run docker
        run: |
          mkdir build
          chmod 777 build
          docker run --rm -v $GITHUB_WORKSPACE:/home/conan/repo conanio/${{ matrix.image }} cmake -DBUILD_TYPE=${{ matrix.build_type }} -P /home/conan/repo/ci/build.cmake
        
  # windows-docker:
  #   strategy:
  #     matrix:
  #       build_type: [Debug, Release]
  #   runs-on: windows-2019
  #   env: 
  #     SOURCE_FOLDER: repo
  #   steps:
  #     - uses: actions/checkout@master
  #     - name: build docker
  #       run: docker build -f ci\\Dockerfile.vs -t msvc_16 .
  #     - name: run docker
  #       run: docker run --rm -v %GITHUB_WORKSPACE%:C:\Users\ContainerAdministrator\%SOURCE_FOLDER% --env BUILD_TYPE=${{ matrix.build_type }} --env SOURCE_FOLDER=%SOURCE_FOLDER% msvc_16 C:\\Users\\ContainerAdministrator\\%SOURCE_FOLDER%\\ci\\build.bat

  windows-native:
    strategy:
      matrix:
        build_type: [Debug, Release]
    runs-on: windows-2019
    env: 
      CC: cl.exe
      CXX: cl.exe
    steps:
      - uses: actions/checkout@master
      - name: install conan
        run: pip install conan
      - name: build
        shell: cmd
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          call cmake -DBUILD_TYPE=${{ matrix.build_type }} -P ci/build.cmake
